name: vllm-gcp-stack

version: "3.9"

services:
  vllm:
    image: vllm/vllm-openai:latest
    restart: unless-stopped
    ports:
      - "${VLLM_PORT:-8000}:8000"
    environment:
      - VLLM_WORKER_USE_FLASH_ATTENTION=false
      - HF_TOKEN=${HF_TOKEN}
      - VLLM_LOGGING_LEVEL=INFO
      - VLLM_PROMETHEUS_ENABLE=true
    command: >
      --model ${MODEL_NAME:-Qwen/Qwen2.5-7B-Instruct}
      --host 0.0.0.0 --port 8000
      --max-model-len 4096
      --tensor-parallel-size 1
      --gpu-memory-utilization 0.90
      --enable-prefix-caching
      --max-num-seqs 32
      --enable-prometheus
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./provision/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./provision/prometheus/alerting_rules.yml:/etc/prometheus/alerting_rules.yml:ro
    ports:
      - "${PROM_PORT:-9090}:9090"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_DEFAULT_THEME=light
    volumes:
      - ./provision/grafana/provisioning:/etc/grafana/provisioning
      - ./provision/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    depends_on: [prometheus, loki]

  loki:
    image: grafana/loki:2.9.8
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./provision/loki/loki-config.yml:/etc/loki/config.yml:ro
    ports:
      - "${LOKI_PORT:-3100}:3100"

  promtail:
    image: grafana/promtail:2.9.8
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./provision/loki/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  node_exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    network_mode: "host"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    privileged: true
    # no host port published; Prometheus scrapes cadvisor:8080 inside the compose network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
