global:
scrape_interval: 5s
scrape_configs:
- job_name: 'vllm'
static_configs:
- targets: ['vllm:8000']
metrics_path: /metrics
- job_name: 'dcgm'
static_configs:
- targets: ['dcgm-exporter:9400']
- job_name: 'node'
static_configs:
- targets: ['localhost:9100']
- job_name: 'cadvisor'
static_configs:
- targets: ['cadvisor:8080']
