name: build-and-push
on:
push:
branches: [ main ]


env:
IMAGE_NAME: ghcr.io/<youruser>/vllm-gcp-demo
BASE_IMAGE: vllm/vllm-openai:v0.9.2


jobs:
build:
runs-on: ubuntu-latest
permissions:
contents: read
packages: write
steps:
- uses: actions/checkout@v4
- name: Login to GHCR
uses: docker/login-action@v3
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Generate Dockerfile
run: |
cat > Dockerfile <<'EOF'
FROM ${BASE_IMAGE}
# Add any customizations (plugins, tokens via runtime env)
# e.g., install jq for debugging
RUN apt-get update && apt-get install -y jq && rm -rf /var/lib/apt/lists/*
EOF
- name: Build & Push
uses: docker/build-push-action@v6
with:
context: .
push: true
tags: |
${{ env.IMAGE_NAME }}:latest
${{ env.IMAGE_NAME }}:${{ github.sha }}
